# UFW DATABASE
- name: Allow PostgreSQL port
  ufw:
    rule: allow
    port: "{{ db_port }}"
    proto: tcp
  tags: ufw

- name: Allow Prometheus port
  ufw:
    rule: allow
    port: "{{ prometheus_port }}"
    proto: tcp
  tags: ufw

- name: Allow Grafana port
  ufw:
    rule: allow
    port: "{{ grafana_port }}"
    proto: tcp
  tags: ufw

- name: Allow cAdvisor port
  ufw:
    rule: allow
    port: "8080"
    proto: tcp
  tags: ufw

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  tags: ufw

# POSTGRESQL
- name: Create postgresql directory
  file:
    path: /home/{{ username }}/postgresql
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  tags: postgresql

- name: Create docker-compose postgresql
  template:
    src: postgresql.yml.j2
    dest: /home/{{ username }}/postgresql/docker-compose.yml
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: postgresql

- name: Deploy PostgreSQL
  shell: |
    cd /home/{{ username }}/postgresql
    docker compose up -d
  become_user: "{{ username }}"
  tags: postgresql

# SONARQUBE DATABASE
- name: Create sonarqube user and database
  shell: |
    docker exec postgresql psql -U {{ db_user }} -d {{ db_name }} -c "CREATE USER sonar WITH PASSWORD 'sonar';" || true
    docker exec postgresql psql -U {{ db_user }} -d {{ db_name }} -c "CREATE DATABASE sonarqube OWNER sonar;" || true
    docker exec postgresql psql -U {{ db_user }} -d {{ db_name }} -c "GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonar;" || true
  tags: sonarqube-db
