---
# CREATE USER
- name: Create user {{ username }}
  user:
    name: "{{ username }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present
  tags: user

- name: Create .ssh directory
  file:
    path: /home/{{ username }}/.ssh
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0700'
  tags: user

- name: Copy SSH public key
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: user

- name: Allow sudo without password
  lineinfile:
    path: /etc/sudoers
    line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
    validate: 'visudo -cf %s'
  tags: user

- name: Disable login user ubuntu
  user:
    name: ubuntu
    password_lock: true
    shell: /usr/sbin/nologin
  tags: user

# SSH HARDENING
- name: Create SSH socket override directory
  file:
    path: /etc/systemd/system/ssh.socket.d
    state: directory
    mode: '0755'
  tags: ssh

- name: Change SSH port to {{ ssh_port }}
  copy:
    dest: /etc/systemd/system/ssh.socket.d/listen.conf
    content: |
      [Socket]
      ListenStream=
      ListenStream={{ ssh_port }}
      ListenStream=0.0.0.0:{{ ssh_port }}
  tags: ssh

- name: Enable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  tags: ssh

- name: Enable pubkey authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
  tags: ssh

- name: Reload systemd and restart SSH socket
  systemd:
    daemon_reload: yes
    name: ssh.socket
    state: restarted
  tags: ssh

# UFW
- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes
  tags: ufw

- name: Allow old SSH port (22)
  ufw:
    rule: allow
    port: "22"
    proto: tcp
  tags: ufw

- name: Allow SSH port (6969)
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
  tags: ufw

- name: Allow Node Exporter
  ufw:
    rule: allow
    port: "{{ node_exporter_port }}"
    proto: tcp
  tags: ufw

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  tags: ufw

# Tutup Port 22
- name: Deny old SSH port (22)
  ufw:
    rule: deny
    port: "22"
    proto: tcp
  tags: close_old_ssh
