---
- name: Server Setup (all servers)
  hosts: all
  become: yes
  roles:
    - server

- name: Setup Docker Server
  hosts: docker_server
  become: yes
  roles:
    - docker-server

#- name: Gateway Setup
#  hosts: gateway
#  become: yes
#  roles:
#    - gateway
#
- name: Appserver Setup
  hosts: apps
  become: yes
  roles:
    - appserver

- name: Database Setup
  hosts: database
  become: yes
  roles:
    - database

- name: Registry Setup
  hosts: apps
  become: yes
  roles:
    - registry
#
#- name: Monitoring Setup
#  hosts: database
#  become: yes
#  roles:
#    - monitoring
